version: '3.9'
services:
  db:
    container_name: bank-db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: simple_bank
    tty: true
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '8080:8080'
  #   environment:
  #     - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
  #   depends_on:
  #     - postgres
  #   entrypoint: ['/app/wait-for.sh', 'postgres:5432', '--', '/app/start.sh']
  #   command: ['/app/main']
